### ISSUE TITLE
Support for Tags or Chips

### ISSUE THREAD

**Issue by capturemathan** [SiddharthSham/spirit#2]
Kudos mate to your first CSS framework :tada:
Just a small recommendation, the framework is fully apt for any newbie to start a blogging site like Medium since the typography, links resemble the same. The addition of tags or chips can enable such users to `highlight words` in between phrases.

**Comment by SiddharthSham** [comment]
Thanks mate!

Not to worry, a Bulma-like tag element is in the works. Right now, it's possible to compose the tag style by:

```
<span class="bg-black white p-1>Some text here</span>
```

Feel free to submit a PR with your own fixes. 😁

**Comment by capturemathan** [comment]
> Thanks mate!
> 
> Not to worry, a Bulma-like tag element is in the works. Right now, it's possible to compose the tag style by:
> 
> ```
> <span class="bg-black white p-1>Some text here</span>
> ```
> 
> Feel free to submit a PR with your own fixes. 😁

Sure 💯
